package ravn_gpu

CONSTANTS_BIND_SLOTS :: 8
SAMPLER_BIND_SLOTS :: 8
RESOURCE_BIND_SLOTS :: 32
RW_RESOURCE_BIND_SLOTS :: 32

NUM_TOTAL_BIND_SLOTS ::
    CONSTANTS_BIND_SLOTS +
    SAMPLER_BIND_SLOTS +
    RESOURCE_BIND_SLOTS +
    RW_RESOURCE_BIND_SLOTS

SAMPLER_SLOT_SHIFT :: 0
CONSTANTS_SLOT_SHIFT :: SAMPLER_SLOT_SHIFT + SAMPLER_BIND_SLOTS
RESOURCE_SLOT_SHIFT :: CONSTANTS_SLOT_SHIFT + CONSTANTS_BIND_SLOTS
RW_RESOURCE_SLOT_SHIFT :: RESOURCE_SLOT_SHIFT + RESOURCE_BIND_SLOTS
